<?xml version="1.0"?>
<robot name="robot_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="robot_prop.xacro" />

    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="base_width" value="0.1" />
    <xacro:property name="base_height" value="0.01" />
    <xacro:property name="base_radius" value="0.05" />
    <xacro:property name="base_depth" value="0.03" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_depth" value="0.1" />
    <xacro:property name="gripper_radius" value="0.04" />
    <xacro:property name="gripper_length" value="0.05" />

    <material name="grey">
        <color rgba="0.62 0.62 0.62 1" />
    </material>  

    <material name="blue">
        <color rgba="0 0 0.7 1" />
    </material>  

    <material name="green">
        <color rgba="0 1 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material> 

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <link name="base2_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_depth}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="red" />
        </visual>
    </link>

    <link name="arm_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_depth}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
    </link>

    <link name="gripper_link">
        <visual>
            <geometry>
                <cylinder radius="${gripper_radius}" length="${gripper_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint>

    <joint name="base_base2_joint" type="fixed">
        <parent link="base_link" />
        <child link="base2_link" />
        <origin xyz="0 0 ${(base_height / 2.0) +(base_depth / 2.0)}" rpy="0 0 0" />
    </joint>

    <joint name="base2_arm_joint" type="revolute">
        <parent link="base2_link" />
        <child link="arm_link" />
        <origin xyz="0 0 ${(base_depth/2.0) + (arm_depth/2.0)}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" velocity="2.0" effort="200" />
    </joint>

    <joint name="arm_gripper_joint" type="continuous">
        <parent link="arm_link" />
        <child link="gripper_link" />
        <origin xyz="0 0 ${(arm_depth/2.0) + (gripper_length/2.0)}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>   
</robot>